### ISSUE TITLE
Add JPEG XR Support

### ISSUE THREAD

**Issue by rowanmanning** [nodeca/probe-image-size#10]
The service I'm working on serves smaller [JPEG XR](https://en.wikipedia.org/wiki/JPEG_XR) images to browsers which support them, and it'd be useful to be able to report their dimensions too.

Would you be interested in adding this feature, or accepting a PR?

**Comment by puzrin** [comment]
> Would you be interested in adding this feature, or accepting a PR?

PR will be accepted (expect async + sync + 100% coverage)

**Comment by puzrin** [comment]
Please, attach small image samples.

References:

- [Spec](http://www.itu.int/rec/T-REC-T.832) - T.832 (03/09) available for download
- jxrlib [ReadWMIHeader()](https://github.com/curasystems/jxrlib/blob/master/image/decode/strdec.c#L2941)

Also:

- [is-jxr](https://github.com/sindresorhus/is-jxr/blob/master/index.js) - suspicious, because check different signature (should be `WMPHOTO` according to spec?)

**Comment by puzrin** [comment]
@rowanmanning Seems nobody is interested. If you have no plans to implement, i'll close this issue.

**Comment by rowanmanning** [comment]
OK @puzrin, seems sensible – I'd like to work on it but I just haven't found time recently. If I get a chance to do the work then I'll PR something.
